---
title: "Data Wrangling"
author: "Ali Oku"
date: "2025-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
```

```{r}

# Read bulk data
cell_lines_bulk = read.csv("/gpfs/commons/groups/compbio/projects/rf_projects/deconv_data/GSE220608/GSE220605_DataMatrix_Mixture_CellLines_Bulk_RNA-seq.csv.gz",
                           row.names = 1)

cell_lines_bulk_test = read.csv("/gpfs/commons/groups/compbio/projects/rf_projects/deconv_data/GSE220608/GSE220605_DataMatrix_Mixture_CellLines_Bulk_RNA-seq.csv.gz",
                           row.names = 1)

```


```{r}

#Read gencode to map gene names to ensebl id 
gene_info <- read.csv("/gpfs/commons/groups/compbio/projects/CZI_endom/RNA_temp/gene_names_gene_ids_czi_endo.csv")


#map ensebl ids to gene symbols 
ensembl_to_gene_symbol_map <- setNames(gene_info$gene_id, gene_info$gene_name)

ensembl_to_gene_symbol_map_v2 <- setNames(gene_info$gene_name, gene_info$gene_id)


```


```{r}

library(biomaRt)
mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

mapping <- getBM(
    attributes = c("hgnc_symbol", "ensembl_gene_id"),
    filters = "hgnc_symbol",
    values = rownames(cell_lines_bulk),
    mart = mart
)

```


```{r}

rownames(cell_lines_bulk)[!rownames(cell_lines_bulk) %in% mapping$hgnc_symbol]

```



```{r}

temp <- ifelse(substr(rownames(cell_lines_bulk), 1, 4) == "ENSG", rownames(cell_lines_bulk), 
       unname(ensembl_to_gene_symbol_map[rownames(cell_lines_bulk)]))

# Remove NULL values
cell_lines_bulk <- cell_lines_bulk[!is.na(temp), ]
temp <- temp[!is.na(temp)]

# Remove duplicated values
cell_lines_bulk <- cell_lines_bulk[!duplicated(temp), ]
temp <- temp[!duplicated(temp)]

# Add ensembl IDs as rownames
rownames(cell_lines_bulk) <- temp

```



```{r}

cell_lines_bulk <- cell_lines_bulk %>% t()

colnames(cell_lines_bulk) <- unname(ensembl_to_gene_symbol_map_v2[colnames(cell_lines_bulk)])

```

```{r}

# Save results
write.csv(cell_lines_bulk, "/gpfs/commons/groups/compbio/projects/rf_projects/deconv_data/GSE220608/GSE220605_DataMatrix_Mixture_CellLines_Bulk_RNA-seq_gene_symbols.csv")

```

```{r}

pseudobulk <- read.csv("/gpfs/commons/groups/compbio/projects/ao_projects/ml_deconv_data/cell_lines/train/pseudobulk_counts.csv",
                            )

cell_lines_bulk <- read.csv("/gpfs/commons/groups/compbio/projects/rf_projects/deconv_data/GSE220608/GSE220605_DataMatrix_Mixture_CellLines_Bulk_RNA-seq_gene_ids.csv",
                            row.names = 1)

cell_lines_bulk <- cell_lines_bulk %>% t()

#write.csv(cell_lines_bulk, "/gpfs/commons/groups/compbio/projects/rf_projects/deconv_data/GSE220608/GSE220605_DataMatrix_Mixture_CellLines_Bulk_RNA-seq_gene_ids.csv")

```


