[project]
name = "DECONVersation"
version = "0.0.1"
authors = [
  { name="Ali Oku", email="aoku@nygenome" },
  { name="Rui Fu", email="rfu@nygenome" }
]
description = "DECONVersation is a tool designed for the deconvolution of bulk RNA-seq data using embeddings derived from large-scale, LLM-based foundation models. DECONVersation produces robust  cell type proportions by leveraging these high-dimensional embeddings to mitigate batch effects typically present in single-cell reference signature matrices."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Eastmanmd/DECONVersation"
Issues = "https://github.com/Eastmanmd/DECONVersation/issues